[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/health/live"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Memory and resource limits - increased for full version with agents
memoryLimit = "2GB"
cpuLimit = "1500m"

# Startup configuration with full mode enabled
startCommand = "RAILWAY_FULL=true python /app/scripts/start.py"

# Environment-specific overrides
[environments.production]
memoryLimit = "4GB"
cpuLimit = "2000m"

[environments.staging]
memoryLimit = "1GB"
cpuLimit = "1000m"