[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/health/railway"
healthcheckTimeout = 300  # 5 minutes - extended for agent loading
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3  # Reduced retries to prevent endless loops

# Memory and resource limits - Railway optimized for full features
memoryLimit = "1GB"  # Reduced but sufficient for optimized version
cpuLimit = "1000m"   # Railway-appropriate CPU allocation

# Startup configuration - DIRECT uvicorn startup from /app directory
startCommand = "python -m uvicorn src.main:app --host 0.0.0.0 --port 8080 --workers 1 --timeout-keep-alive 30"

# Force environment variable for agent loading
[environments.production.variables]
RAILWAY_FULL = "true"
ENABLE_AGENT_LOADING = "true"

# Environment-specific overrides
[environments.production]
memoryLimit = "2GB"   # Production with more resources
cpuLimit = "1500m"
# Use full mode in production with all features
RAILWAY_FULL = "true"

[environments.staging] 
memoryLimit = "1GB"   # Staging uses optimized mode
cpuLimit = "1000m"
# ENABLE_AGENT_LOADING = "true"

[environments.development]
memoryLimit = "512MB" # Development minimal resources
cpuLimit = "500m"
# RAILWAY_MINIMAL = "true"