[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/health/railway"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Memory and resource limits for LangGraph + FastAPI
memoryLimit = "2GB"
cpuLimit = "1500m"

# Production startup with both services
startCommand = "python /app/scripts/start_production.py"

[environments.production.variables]
RAILWAY_FULL = "true"
ENABLE_AGENT_LOADING = "true"
ENABLE_LANGGRAPH = "true"
LANGGRAPH_API_URL = "http://localhost:8001"

[environments.production]
memoryLimit = "4GB"
cpuLimit = "2000m"

[environments.staging]
memoryLimit = "2GB"
cpuLimit = "1500m"

[environments.development]
memoryLimit = "1GB"
cpuLimit = "1000m"
