[build]
builder = "dockerfile"
dockerfile = "Dockerfile"

[deploy]
healthcheckPath = "/health/live"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Memory and resource limits
memoryLimit = "1GB"
cpuLimit = "1000m"

# Startup configuration
startCommand = "python /app/scripts/start.py"

# Environment-specific overrides
[environments.production]
memoryLimit = "2GB"
cpuLimit = "2000m"

[environments.staging]
memoryLimit = "1GB"
cpuLimit = "1000m"